// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/api/proposals/search.ts";
import * as $4 from "./routes/docs/_layout.tsx";
import * as $5 from "./routes/docs/contracts/index.tsx";
import * as $6 from "./routes/docs/index.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/proposals/index.tsx";
import * as $$0 from "./islands/ProposalList.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/api/proposals/search.ts": $3,
    "./routes/docs/_layout.tsx": $4,
    "./routes/docs/contracts/index.tsx": $5,
    "./routes/docs/index.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/proposals/index.tsx": $8,
  },
  islands: {
    "./islands/ProposalList.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
