name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DENO_AUTH_TOKENS: ${{ secrets.DENO_AUTH_TOKENS }}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.x

      - run: deno task check
