name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  DENO_AUTH_TOKENS: ${{ vars.DENO_AUTH_TOKENS }}
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.x

      - name: Build step
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "daohive-web"
          entrypoint: "main.ts"
          root: "."
