name: Deploy


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# APIError: GitHub event 'workflow_run' is not supported.
# on:
#   workflow_run:
#     workflows: [Check]
#     branches: [main]
#     types: [completed]

env:
  DENO_AUTH_TOKENS: ${{ secrets.DENO_AUTH_TOKENS }}
  MEILI_HOST: ${{ vars.MEILI_HOST }}
  MEILI_MASTER_KEY: ${{ secrets.MEILI_MASTER_KEY }}
  
jobs:
  deploy:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.x

      - name: Build step
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: daohive-web
          entrypoint: main.ts
          root: .
